// Even Fibonacci numbers - Problem 002
// https://projecteuler.net/problem=2

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let sum = 0;

const fib = (n, memo = {}) => {
	if (memo[n]) return memo[n];
	if (n <= 2) return 1;

	memo[n] = fib(n - 1, memo) + fib(n - 2, memo);

	if (memo[n] >= 4000000) {
		return sum;
	} else if (memo[n] % 2 === 0) {
		sum += memo[n];
	}

	return memo[n];
};

console.log(fib(1000));
